In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
new=arr.reshape(1,3,3)
print(new)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]])
new=arr.reshape(3,3)
print(new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]])
new=arr.reshape(9)
print(new)

[1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
new=arr.reshape(9)
print(new)

[1 2 3 4 5 6 7 8 9]
